baseURL = "https://divelab.tech"
defaultContentLanguage = "en"
title = "Deep Dives with Ian"
theme = "kopi"

[params]

	[params.author]
	name = "Ian P."
	bio = "3 giant kelp in a trench coat"
	role = "Cool Guy in Training"

